server:
  port: 8080

spring:
  application:
    name: demo

#  datasource:
#    platform: mysql
#    url: jdbc:mysql://forclass.c8ydsrovkrwj.ap-northeast-2.rds.amazonaws.com/test?autoReconnect=true # 변경해주세요
#    username:  # 변경해주세요
#    password:  # 변경해주세요
#    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
#    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전


  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled=true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Nmjt1915!@